---
title: Sociar
# File that contains your Flickr API key on the first line.
# If not a file, the value will be used as key instead.
flickr: '~/.flickr_api_key'
description: Sociar is an Open Source Social Network Platform
author: manveru
keywords:
  - Open Source
  - Social Network
  - Ramaze
